FROM python:alpine3.9 
COPY . /app
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
# RUN source venv/bin/activate
EXPOSE 5005
ENTRYPOINT [ "python" ] 
CMD [ "app.py" ] 

