version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5001"  
    networks:
      - flask_network

  nginx: 
    image: nginx:latest
    container_name: nginx-compose 
    ports:
      - 8989:80
    networks:
      - flask_network
    

networks:
  flask_network:
    driver: bridge
